 mysql_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 123456@aA
 phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - mysql_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 123456@aA
